apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 111-test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: github
