apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-uat-test-24
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/quicktest-24-frontend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: uat
  owner: group:default/guests
  system: system:default/Regression-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/quicktest-24-frontend
    backstage.io/source-vcs: github
