apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: abcsamplepro
  description: ""
  annotations:
    backstage.io/source-location: http://github.com/abc
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/application999
  dependsOn: []
  dependencyOf: []
