apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: abcsamplepro
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cicd-sasiru-3.git
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/application999
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
