apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: agentnex-cursorfront-dit2
  description: agentnex-cursorfront-dit2
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/agentnex-cursorfront
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: agentnex-cursorfront-DIT-2
    google.com/cloudbuild-project-slug: prj-agentnex-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: dit2
  owner: group:default/agentnex-team
  system: system:default/agentnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/agentnex-cursorfront
    backstage.io/source-vcs: github
