apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: airflow-vm-stage
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/airflow-dev-environment
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: airflow-dev-environment
    google.com/cloudbuild-trigger-name: Platformnex-Airflow-Deploy-Stage
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platform-admin
  system: system:default/Airflow-PlatformNEX
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/airflow-dev-environment
    backstage.io/source-vcs: github
