apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: anno-test-sasiru
  description: anno-test-sasiru
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prj-dev-platform-next
spec:
  type: container
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/platformnex
  lifecycle: development
