apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: apigee-team
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/apigee-dev-portal
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: team
  children: []
  members: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/apigee-dev-portal
    backstage.io/source-vcs: github
