apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: apigee-dev-portal
  description: this is the apigee dev portal application
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/apigee-team
