apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assetnex-qa
  description: assetnex-qa service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/asset-nex
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-service-nex
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: assetnex-qa
    google.com/cloudbuild-trigger-name: ASSETNEX-DIT-QA-UAT
    google.com/cloudbuild-project-slug: prj-dev-service-nex
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: assetnex-qa
  owner: group:default/assetnex-admin
  system: system:default/assetnex
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/asset-nex
    backstage.io/source-vcs: github
