apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: assetnex-db-uat
  description: assetnex-db-uat resource
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: cloud_sql
  owner: group:default/assetnex-admin
  system: system:default/assetnex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-service-nex
  lifecycle: assetnex-uat
