apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authorization-server-dev
  description: authorization server
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-authorization
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex-authorization
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/cloudbuild-trigger-name: platformnex-authorization-trigger-bc8a931a2999434f-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectId: dev
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
