apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authorization-server-dev
  description: authorization server
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-authorization
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex-authorization
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/platformnex
