apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: automation-test-app
  description: jhbjhbihb
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
