apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Catalog35
  description: Catalog35Catalog35Catalog35Catalog35
  annotations:
    backstage.io/source-location: https://github.com/cgs-tech/test-repo2
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/QA-Test-Application
