apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cd
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: dit1
  owner: group:default/guests
  system: system:default/DIT2TriggerTest
  dependsOn: []
  dependencyOf: []
