apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cefe
  description: evervvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
spec:
  type: storage
  owner: group:default/guests
  system: system:default/Platformnex
  region: us-central1
  project: efer
  lifecycle: development
