apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ci-cd-test-qa-2
  description: ci-cd-test-qa-2 description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
