apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicdtest-2
  description: asdfg
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: regression-repo-f-9
spec:
  type: website
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/testappss
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: github
