apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-sasiru-3
  description: https://github.com/ivedha-tech/cicd-sasiru-3
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cicd-sasiru-3
    backstage.io/source-vcs: Github
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
