apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-test-v
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cicd-test-ba
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: cicd-test-ba
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
