apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicdgreen
  description: https://github.com/ivedha-tech/abcdrb
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/abcdrb
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-Application
