apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-vir2
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-repo-cr-30-f
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cicd-vir2-staging-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/UAT-test
  providesApis: []
  consumesApis: []
