apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicdtest
  description: asdfg
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/testappss
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: github
