apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-sasiru
  description: "cicd-sasiru testing cicd-sasiru testing cicd-sasiru testing "
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cicd-sasiru
    backstage.io/source-vcs: Github
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/platformnex
