apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cloud-storage-uat
  description: to store the files/blob in uat
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-service-nex
  lifecycle: uat
