apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudnex-PROD
  description: cloudnex-PROD env service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloudnex
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cloudnex-PROD
    google.com/cloudbuild-project-slug: prj-cloudnex-prod
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: production
  owner: group:default/cloudnex-team
  system: system:default/cloudnex
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloudnex
    backstage.io/source-vcs: github
