apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-configs
  description: this repository contains the onboarded yaml entities such as
    components, apis and resources
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: Github
    mycompany.com/gcp-provider: gcp
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/platformnex
