apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudops-gateway-dit1
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-gateway
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-platformnex-cloudops-gateway-dit1-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-gateway
    backstage.io/source-vcs: github
