apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudops-gateway-uat
  description: gateway to handle cloud functions in uat environment
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-gateway
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: cloudops-gateway
    google.com/cloudbuild-trigger-name: cb-platformnex-cloudops-gateway-uat-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
    jira.com/project-key: PLATNEX
spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-gateway
    backstage.io/source-vcs: github
