apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudforge-be-staging
  description: cloudforge-be-staging component
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloudforge-be
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-v2-backend-qa1
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/CloudForge
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
