apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cloud-cdn
  description: cloud-cdn
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prj-dev-platformnex
spec:
  type: storage
  region: us-central1
  project: prj-dev-platformnex
  owner: group:default/guests
  system: system:default/Platform-Engineering
  lifecycle: development
