apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: componentrelease-17-development
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/com-f-17-dec
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " release-18-f"
    github.com/project-slug: ivedha-tech/com-f-17-dec
    github.com/repo-url: https://github.com/ivedha-tech/com-f-17-dec
    google.com/cloudbuild-trigger-name: componentrelease-17-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: development
  owner: user:default/thushanthini.kulenthiran
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
