apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-green-111-qa
  description: frontend
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/component-green-111
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/component-green-111
    github.com/repo-url: https://github.com/ivedha-tech/component-green-111
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: qa
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/application999
  providesApis: []
  consumesApis: []
