apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comp1609
  description: sdcsfwrf edit
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: qa
  owner: group:default/platformnex-admin
  system: system:default/sanity1609
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: github
