apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dasda
  description: fsd
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ''
    sonarqube.org/project-key: test-qa-f-15
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/new-app-fin
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: github
