apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: data13may
  description: database resource for Regression-28
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: database
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/Regression-28
  lifecycle: development
