apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-test
  description: database resource for BranchTest
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: database
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/BranchTest
  lifecycle: branchtest__sample-ephemeral-env
