apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Demo_Application1
  description: Sample description
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platfor-admin
