apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-28-release-test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/oct-28-frontend
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: dev-28-release-test-development-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
    sonarqube.org/project-key: oct-28-frontend
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Regression-test
  providesApis: []
  consumesApis: []
