apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-f-9
    backstage.io/source-vcs: github
