apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-test
  description: qa-test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/tomfronend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Test
  dependsOn: []
  dependencyOf: []
