apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-test-18
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-regression-feb-f-18
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: platformnex-regression__development
  owner: group:default/platform-admin
  system: system:default/Platformnex-Regression
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-regression-feb-f-18
    backstage.io/source-vcs: github
