apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devops-gateway-prod
  description: devops gateway instance prod environment
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-devops-gateway
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex2
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-devops-gateway-prod
    google.com/cloudbuild-trigger-name: int-prom-prod-devops-2
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
    jira.com/project-key: PEJ
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/platformnex
