apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Dit1-Application
  description: Dit1-Application
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platformnex-team
