apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DIT2TriggerTest
  description: DIT2TriggerTest application info
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/dit2-trigger-test
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: dit2-trigger-test-trigger-43a894025487416796f482b3-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/DIT2TriggerTest
  providesApis: []
  consumesApis: []
