apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: doc-test
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-documentations
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: PEJ
    google.com/cloudbuild-trigger-name: dit-trigger-test-trigger-a69c3439c6fb4ee
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-team
  dependsOn: []
  dependencyOf: []
  system: system:default/platformnex-test
  providesApis: []
  consumesApis: []
