apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DpTest
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-f-t-27
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Test-Application
  providesApis: []
  consumesApis: []
