apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dsafasf
  description: fdsssssssssssssssssssss
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: uat
  owner: group:default/guests
  system: system:default/QA-Test-Application
  dependsOn: []
  dependencyOf: []
