apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecs27-production
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/ecs27
    github.com/repo-url: https://github.com/ivedha-tech/ecs27
    backstage.io/source-location: https://github.com/ivedha-tech/ecs27
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: user:default/thushanthini.kulenthiran
    release-manager/repository: ecs27-production
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/ecs27
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: ecs27-production
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: production
  owner: user:default/thushanthini.kulenthiran
  system: system:default/Platformnex-Regression
