apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f-test-200-development
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/f-test-200
    github.com/repo-url: https://github.com/ivedha-tech/f-test-200
    backstage.io/source-location: https://github.com/ivedha-tech/f-test-200
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-team
    release-manager/repository: f-test-200-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/f-test-200
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: f-test-200-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-team
  system: system:default/Catalog-test
  created_by: sasiru.wijendra@ivedha.com
