apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fdfd
  description: fdsfs
  annotations:
    backstage.io/source-location: https://github.com/sfgfdfgdgfd/gfgdfgdf
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/greenfield
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/sfgfdfgdgfd/gfgdfgdf
    backstage.io/source-vcs: github
