apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fdfd
  description: fdsfs
  annotations:
    backstage.io/source-location: https://github.com/sfgfdfgdgfd/gfgdfgdf
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: platformnex-authorization-DIT-1
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1-a
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/greenfield
  providesApis: []
  consumesApis: []
