apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fdfsdfd
  description: fsdfd
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/qa-teamforchecking
