apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fe-test-04-b-development
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/fe-test-04-b
    github.com/repo-url: https://github.com/ivedha-tech/fe-test-04-b
    backstage.io/source-location: https://github.com/ivedha-tech/fe-test-04-b
    backstage.io/language: go
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/guests
    release-manager/repository: fe-test-04-b-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/fe-test-04-b
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: fe-test-04-b-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Dev-Test
  created_by: sasiru.wijendra@ivedha.com
