apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: featuretest-stage
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-qa-1-frontend
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: repo-qa-1-frontend
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing tableId
    mycompany.com/gcp-table-id: billing_summary_daily
spec:
  type: service
  lifecycle: catalog-test__staging
  owner: group:default/platformnex-team
  dependsOn: []
  dependencyOf: []
  system: system:default/Catalog-test
  providesApis: []
  consumesApis: []
