apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feb-regression-26-f-service-uat
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/feb-regression-26-f
    github.com/repo-url: https://github.com/ivedha-tech/feb-regression-26-f
    backstage.io/source-location: https://github.com/ivedha-tech/feb-regression-26-f
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platform-admin
    release-manager/repository: feb-regression-26-f-service-uat
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/feb-regression-26-f
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: feb-regression-26-f-service-uat
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: uat
  owner: group:default/platform-admin
  system: system:default/Platformnex-Regression
  created_by: thushanthini.kulenthiran@ivedha.com
