apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: finnnnn
  description: fsddfssssssssssssssssssssssssssssss
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/new-app
  dependsOn: []
  dependencyOf: []
