apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-uat
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: prod-1-production-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-provisioning
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: platformnex__uat
  owner: group:default/guests
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: github
