apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-release-17-development
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/f-release-dec-17
    github.com/repo-url: https://github.com/ivedha-tech/f-release-dec-17
    backstage.io/source-location: https://github.com/ivedha-tech/f-release-dec-17
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: user:default/thushanthini.kulenthiran
    release-manager/repository: frontend-release-17-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/f-release-dec-17
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: frontend-release-17-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: development
  owner: user:default/thushanthini.kulenthiran
  system: system:default/Platformnex-Regression
