apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gbd
  description: dfgdfgdgdfgdffdfsfdsfdfsd
  annotations:
    backstage.io/source-location: https://github.com/kushanD95/swag-test-temp100
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/DitTriggerTest
  providesApis: []
  consumesApis: []
