apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gc-regression-service-development
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/gc-regression
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/gc-regression
    github.com/repo-url: https://github.com/ivedha-tech/gc-regression
    google.com/cloudbuild-trigger-name: gc-regression-service-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
