apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gcs-airflow-release-notes-events
  description: gcs-airflow-release-notes-events
  annotations:
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  region: us-central1
  project: prj-prd-cnb-workload
  lifecycle: production
