apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops-config
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/gitops-configs
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platformnex-salesforce-team
  dependsOn: []
  dependencyOf: []
  system: system:default/platformnex-salesforce
  providesApis: []
  consumesApis: []
