apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello_world
  description: some info about hello word app (tested)
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/cloud_configs/edit/feature-yaml-dit2/applications/hello_world.yaml
    backstage.io/source-vcs: Github
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/HelloWorld
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
