apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworld_backend
  description: some info about hello world backend app
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/hello-world
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/helloworld
