apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jir
  description: jirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjirjir
  annotations:
    backstage.io/source-location: url:url:https://github.com/cgs-tech/test-repo-2
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: production
  owner: group:default/guests
  system: system:default/Test-Application
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
