apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KT
  description: qa kt
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-test-f-22
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Test-Application
  providesApis: []
  consumesApis: []
