apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: library
  description: https://github.com/ivedha-tech/cloudforge-fe
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloudforge-fe
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/sampleappli
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloudforge-fe
    backstage.io/source-vcs: github
