apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: LocalHello3
  description: LocalHello3 about the application section
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/hello-world
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/LocalHelloWorld
