apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: LyricSense
  description: https://github.com/Nithursika/LyricSense
  annotations:
    sonarqube.org/project-key: platformnexghgbbr5t
