apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: LyricSense
  description: https://github.com/Nithursika/LyricSense
  annotations:
    backstage.io/source-location: https://github.com/Nithursika/LyricSense
    backstage.io/source-vcs: Github
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    jira.com/project-key: PEJ
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-App
