apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: machine-learning-apps
  description: this is a machine learning app
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platform-admin
