apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: management-portal-prod
  description: Management Portal service prod env
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-management
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-management-prod
    google.com/cloudbuild-trigger-name: int-prom-prod-management-9
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ''
    jira.com/project-key: PLATNEX
    sonarqube.org/project-key: platformnex-management
spec:
  type: service
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-management
    backstage.io/source-vcs: github
