apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: management-portal-dev
  description: Management Portal service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-management
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-management
    backstage.io/source-vcs: github
