apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mn
  description: j
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-4-f-repo
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-4-f-repo
    backstage.io/source-vcs: github
