apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-bucket-123
  description: storage resource for Catalog-test
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
spec:
  type: storage
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Catalog-test
  providesApis: []
  consumesApis: []
