apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: NATS-staging
  description: event broker for orchestrator and backend staging
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
spec:
  type: cloud_run
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: staging
