apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: new-Test-Application
  description: new-Test-Application
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platfor-admin
