apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: new-postgres-db
  description: Existing database resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: cloudsql
  owner: guests
  system: system:default/platformnex
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
  created_by: sanuka.dayarathne@ivedha.com

