apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-com-wed-g-009-dev
  description: frontend
  annotations:
    github.com/project-slug: ivedha-tech/new-com-wed-g-009
    github.com/repo-url: https://github.com/ivedha-tech/new-com-wed-g-009
    backstage.io/source-location: https://github.com/ivedha-tech/new-com-wed-g-009
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/guests
    release-manager/repository: new-com-wed-g-009
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/new-com-wed-g-009
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-trigger-name: new-com-wed-g-009-dev

spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/dsa