apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-com-dit2-test-development
  description: Backend
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/new-com-dit2
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/new-com-dit2
    github.com/repo-url: https://github.com/ivedha-tech/new-com-dit2
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: new-com-dit2-test-development
    google.com/cloudbuild-trigger-name: new-com-dit2-test-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: billing_summary_daily
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/appleveltesting
  providesApis: []
  consumesApis: []
