apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: new-com-test701-development
  description: Existing triggers resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: cloudbuild
  owner: group:default/platformnex-team
  system: system:default/Catalog-test
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
  created_by: nithursika.kalanantharasan@ivedha.com

