apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-com-greenfield001-qa
  description: frontend
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/new-com-greenfield001
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/new-com-greenfield001
    github.com/repo-url: https://github.com/ivedha-tech/new-com-greenfield001
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: qa
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/application999
  providesApis: []
  consumesApis: []
