apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-test-prod-service-dit1
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/new-test-prod
    github.com/repo-url: https://github.com/ivedha-tech/new-test-prod
    backstage.io/source-location: https://github.com/ivedha-tech/new-test-prod
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: new-test-prod-service-dit1
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/new-test-prod
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: new-test-prod-service-dit1
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
