apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PE-Frontend
  description: PE Frontend Repo
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex-frontend
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: dit2
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/HelloWorld2
  providesApis: []
  consumesApis: []
