apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Pe-onboardcomponent
  description: regression
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ''
    google.com/cloudrun-location: ''
    google.com/cloudrun-service-name: ''
    google.com/gcp-projectid: prj-platformnex-prod
    mycompany.com/gcp-projectid: prj-platformnex-prod
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: billing_summary_daily
    sonarqube.org/project-key: qa-re-1
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
