apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pe-regression
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: ds_billing
    google.com/cloudrun-service-name: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
