apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pe-sync-test
  description: "some info "
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platformnex-team
