apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pe-test-resource-retry
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/count2-frontend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: "platformnex-test__dit2 "
  owner: group:default/guests
  system: system:default/platformnex-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/count2-frontend
    backstage.io/source-vcs: github
