apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-backend-stage
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-backend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-team
  system: system:default/platformnex-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-backend
    backstage.io/source-vcs: github
