apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-backend-2
  description: some info about app info
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-backend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: test-pe-ankur-new__development
  owner: group:default/platformnex-team
  system: system:default/test-pe-ankur-new
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-backend
    backstage.io/source-vcs: github
