apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-frontend-staging
  description: frontend to the developer portal's staging environment
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex-frontend
    pulumi.com/project-slug: mcmuralishclint/pulumi-cicd/dev
    pulumi.com/orga-slug: mcmuralishclint
    google.com/cloudbuild-trigger-name: cb-platformnex-frontend-qa-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
    jira.com/project-key: PEJ
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: billing_summary_daily
spec:
  type: website
  lifecycle: qa
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: github
