apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-orchestrator-job-runner-qa
  description: A Rust-based HTTP service that provides an endpoint to launch Cloud
    Run jobs by executing the cloud-run-job.sh script.
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-orchestrator-job-runner
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-platformnex-orchestrator-job-runner-qa-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: qa
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-orchestrator-job-runner
    backstage.io/source-vcs: github
