apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-salesforce-orchestrator-QA
  description: platformnex-salesforce-orchestrator-QA env service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-orchestrator
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: platformnex-salesforce-orchestrator-QA
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: qa
  owner: group:default/platformnex-salesforce-team
  system: system:default/platformnex-salesforce
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-orchestrator
    backstage.io/source-vcs: github
