apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-salesforce-frontend-dev
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-frontend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: platformnex-salesforce__development
  owner: group:default/platformnex-team
  system: system:default/platformnex-salesforce
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-frontend
    backstage.io/source-vcs: github
