apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: platformnex-db
  description: platformnex-db onboard
spec:
  type: storage
  owner: group:default/guests
  region: us-central1
  project: prj-dev-platform-next
