apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-orchestrator-dev
  description: this is the orchestrator instance for dev envrironment
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-orchestrator
    backstage.io/source-vcs: Github
    jira.com/project-key: PEJ
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/platformnex
