apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-authorization
  description: test platformnex-authorization
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-authorization
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: platformnex-test__development
  owner: group:default/platformnex-team
  system: system:default/platformnex-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-authorization
    backstage.io/source-vcs: github
