apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Platform-Engineering
  description: Platform Engineering services and Resources
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platformnex-admin
