apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-orchestrator-staging
  description: this is the orchestrator instance for staging environment
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-orchestrator
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/platformnex
