apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: platformnex-backend
  description: PlatformNex Backend Service
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/platformnex-backend
    backstage.io/source-vcs: Github
spec:
  type: grpc
  lifecycle: development
  owner: group:default/Test-Application
  system: system:default/platformnex
  definition: syntax = "proto3";service Exampler {  rpc Example (ExampleMessage)
    returns (ExampleMessage) {};}message ExampleMessage {  string example = 1;};
