apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Platformfrontend
  description: Platformnex test frontent component
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/Test-Applications
