apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: platformnex-dev
  description: Existing database resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: cloudsql
  owner: group:default/platformnex-team
  system: system:default/test-pe-ankur
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
  created_by: ankur.sharma@ivedha.com

