apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platformnex-frontend-prod
  description: frontend to the developer portal
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
    artifact-registry/repository: us-central1-docker.pkg.dev/prj-platformnex-prod/platformnex/platformnex-v2-frontend-prod
    pulumi.com/project-slug: mcmuralishclint/pulumi-cicd/dev
    pulumi.com/orga-slug: mcmuralishclint
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-v2-frontend-prod
    google.com/cloudbuild-trigger-name: int-prom-prod-frontend-1
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    jira.com/project-key: PEJ
spec:
  type: website
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/platformnex
