apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pn_dit2_app
  description: Cloud sql database for dev environment app
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-prod/applications/
    google.com/gcp-projectid: ""
spec:
  type: cloud_sql
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
