apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pn_prod_news-feedback-clone
  description: This the pn_prod_news-feedback DB
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
spec:
  type: cloud_sql
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  region: us-central1
  project: prj-platformnex-prod
  lifecycle: production
