apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pn_prod_app
  description: Cloud sql database for dev prod app
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
spec:
  type: storage
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: production
