apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PNEX-Frontend
  description: This is a feature testing repository
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platform-feature-test
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-frontend
    google.com/gcp-projectid: prj-dev-platform-next
    jira.com/project-key: PEJ
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
    sonarqube.org/project-key: platform-feature-test
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/PNEX-Engineering
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platform-feature-test
    backstage.io/source-vcs: github
