apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pnex-sto-bucket3
  description: pnex-sto-bucket3
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prj-dev-platform-next
spec:
  type: storage
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/Platformnex
  lifecycle: development
