apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc-comp
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-ga-three-t-001-fe
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
    google.com/cloudbuild-trigger-name: poc-comp-development-trigger
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/POC
  providesApis: []
  consumesApis: []
