apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc-comp
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-ga-three-t-001-fe
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/POC
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-ga-three-t-001-fe
    backstage.io/source-vcs: github
