apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-development
  description: database to store the servicenex info
spec:
  type: cloud_sql
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
