apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-uat
  description: database to store the servicenex info in uat
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cloud_configs
    backstage.io/source-vcs: github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: cloud_sql
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: uat
