apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-qa-service-development
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prod-qa
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: repo-prod-f-26
    github.com/project-slug: ivedha-tech/prod-qa
    github.com/repo-url: https://github.com/ivedha-tech/prod-qa
    google.com/cloudbuild-trigger-name: prod-qa-service-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
