apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: production-testrepo-qa-f
  description: production-testrepo-qa-f description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: frontend-service
    google.com/cloudbuild-trigger-name: frontend-service
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: production
  owner: group:default/guests
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
