apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-1
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/dev-test
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-platform-provisioning
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: prod-1-production
    google.com/cloudbuild-trigger-name: prod-1-production-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-provisioning
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: production
  owner: group:default/development-team
  dependsOn: []
  dependencyOf: []
  system: system:default/Regression-28
  providesApis: []
  consumesApis: []
