apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-test-17-service-staging
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prod-test-17
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " prod-test-17"
    github.com/project-slug: ivedha-tech/prod-test-17
    github.com/repo-url: https://github.com/ivedha-tech/prod-test-17
    google.com/cloudbuild-trigger-name: prod-test-17-service-staging
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
