apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-ui-f-service-uat
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/prod-ui-f
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: prod-ui-f
    github.com/project-slug: test-platformnex/prod-ui-f
    github.com/repo-url: https://github.com/test-platformnex/prod-ui-f
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: prod-ui-f-service-uat
    google.com/cloudbuild-trigger-name: prod-ui-f-service-uat
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
