apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-env-qa-test
  description: prod-env-qa-test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regressionrepo-qa-f-12
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: production
  owner: group:default/guests
  system: system:default/Test-Application
  dependsOn: []
  dependencyOf: []
