apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: prod-store-26
  description: New Storage resource to be created
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: storage
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  region: us-central1
  project: prj-platformnex-prod
  lifecycle: values.environment
  created_by: thushanthini.kulenthiran@ivedha.com

