apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-28
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prod-tech-repo-frontend
    backstage.io/source-vcs: Github
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prod-tech-repo-frontend
    backstage.io/source-vcs: github
