apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: prov-ssd2
  description: prov-ssd2
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prj-dev-platform-provisioning
spec:
  type: storage
  region: us-central1
  project: prj-dev-platform-provisioning
  owner: group:default/guests
  system: system:default/HelloWorld2
  lifecycle: development
