apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pw-resource-1778524539644
  description: Playwright automation onboarding validation
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/guests
  system: system:default/PE-Regression
  region: us-central1
  project: prj-dev-platform-provisioning
  lifecycle: development
