apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-22-cicd-b-development
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/qa-22-cicd-b
    github.com/repo-url: https://github.com/ivedha-tech/qa-22-cicd-b
    backstage.io/source-location: https://github.com/ivedha-tech/qa-22-cicd-b
    backstage.io/language: go
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platform-admin
    release-manager/repository: qa-22-cicd-b-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/qa-22-cicd-b
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: qa-22-cicd-b-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-project-slug: values.cloudbuild_project_slug || "
    google.com/cloudrun-location: values.cloudbuild_location || "us-central1

spec:
  type: service
  lifecycle: development
  owner: group:default/platform-admin
  system: system:default/PE-regression-22
  created_by: thushanthini.kulenthiran@ivedha.com
