apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-csg
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/cgs-tech/test-repo-2
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/development-team
  system: system:default/Regression-17
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/cgs-tech/test-repo-2
    backstage.io/source-vcs: github
