apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-prod-env
  description: qa-prod-env description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-f-qa-aug-12
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: testrepo-f-qa-aug-12
spec:
  type: service
  lifecycle: production
  owner: group:default/guests
  system: system:default/Platformnex
  dependsOn: []
  dependencyOf: []
