apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-stage-env
  description: qa-stage-env description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-f-qa-aug-12
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
