apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-test-dev
  description: qa-test-dev description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: testrepo-qa-f-aug1-trigger-d1a0a771bad94fbda1d8fe9-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
