apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-test
  description: qa-test test description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/platformnex
