apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-test-12
  description: qa-test-12 description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/cloudbuild-trigger-name: srnext-10-be-31483-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
  subcomponentOf: component:default/qa-test-13
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: github
