apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qatest
  description: test-qa-06 test description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
