apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qatestcatalogedit_dev
  description: https://github.com/ivedha-tech/qatestcatalogedit
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qatestcatalogedit
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/qatestcatalogedit
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qatestcatalogedit
    backstage.io/source-vcs: github
