apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: re-june26cache
  description: cache resource for Regression-test
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: cache
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/Regression-test
  lifecycle: regression-test__development
