apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RE-june12
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-provisioning
spec:
  type: service
  lifecycle: regression-test-13__development
  owner: group:default/development-team
  dependsOn: []
  dependencyOf: []
  system: system:default/regression-test-13
  providesApis: []
  consumesApis: []
