apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-front-01-service-development
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/react-front-01
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: values.cloudbuild_project_slug
    google.com/cloudrun-location: values.cloudbuild_location
    google.com/cloudrun-service-name: "-"
    google.com/cloudbuild-trigger-name: react-front-01-service-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: catalog-test__development
  owner: group:default/platformnex-team
  system: system:default/Catalog-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/react-front-01
    backstage.io/source-vcs: github
