apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: recahemay26
  description: cache resource for Dev-Test
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: cache
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/Dev-Test
  lifecycle: dev-test__staging
