apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reg-6-qa-service-staging
  description: created by template
  annotations:
    github.com/project-slug: test-platformnex/reg-6-qa
    github.com/repo-url: https://github.com/test-platformnex/reg-6-qa
    backstage.io/source-location: https://github.com/test-platformnex/reg-6-qa
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: reg-6-qa-service-staging
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/reg-6-qa
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: reg-6-qa-service-staging
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: reg-6-qa-service-staging

spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/Regression-6
  created_by: thushanthini.kulenthiran@ivedha.com
