apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: reg-test-26-aug
  description: testing application
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
