apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reg-test-comp-13oct-clone
  description: testing
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: test-qa-f-15
    google.com/gcp-projectid: ''
spec:
  type: service
  lifecycle: production
  owner: group:default/platfor-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/reg-test-13-oct
  providesApis: []
  consumesApis: []
