apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: reg26sep-res
  description: daffdasd
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platfor-admin
  system: system:default/reg26sep-ssg
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
