apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: REGRESSION
  description: database resource for Platformnex-Regression
  annotations:
    backstage.io/source-location: https://github.com/prj-platformnex-prod
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: database
  region: us-central1
  project: prj-platformnex-prod
  owner: group:default/guests
  system: system:default/Platformnex-Regression
  lifecycle: development
