apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-qa-gcon-1-service-production
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/regression-qa-gcon-1
    backstage.io/source-vcs: Github
    github.com/project-slug: test-platformnex/regression-qa-gcon-1
    github.com/repo-url: https://github.com/test-platformnex/regression-qa-gcon-1
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: regression-qa-gcon-1-service-production
    google.com/cloudbuild-trigger-name: regression-qa-gcon-1-service-production
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
    mycompany.com/gcp-projectid: prj-platformnex-prod
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: billing_summary_daily
spec:
  type: service
  lifecycle: production
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
