apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-nov-4
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/customernov3backend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/StackPilot
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/customernov3backend
    backstage.io/source-vcs: github
