apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-f-development
  description: created by template
  annotations:
    github.com/project-slug: test-platformnex/regression-f
    github.com/repo-url: https://github.com/test-platformnex/regression-f
    backstage.io/source-location: https://github.com/test-platformnex/regression-f
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: regression-f-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/regression-f
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: regression-f-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
    google.com/cloudrun-project-slug: values.cloudbuild_project_slug || "
    google.com/cloudrun-location: values.cloudbuild_location || "us-central1

spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: thushanthini.kulenthiran@ivedha.com
