apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-01-uat
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/k8-test
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: pe-regression-22__development
  owner: group:default/platform-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/PE-regression-22
  providesApis: []
  consumesApis: []
