apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: regressionmay26
  description: ""
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platformnex-admin
