apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regressiondec16t-service-staging
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/regressiondec16t
    github.com/repo-url: https://github.com/ivedha-tech/regressiondec16t
    backstage.io/source-location: https://github.com/ivedha-tech/regressiondec16t
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/development-team
    release-manager/repository: regressiondec16t-service-staging
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/regressiondec16t
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: regressiondec16t-service-staging
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: staging
  owner: group:default/development-team
  system: system:default/Platformnex-Regression
