apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-pe-service-production
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-pe
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/regression-pe
    github.com/repo-url: https://github.com/ivedha-tech/regression-pe
    google.com/cloudbuild-trigger-name: regression-pe-service-production
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-pe
    backstage.io/source-vcs: github
