apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-m-17-service-testjan
  description: created by template
  annotations:
    github.com/project-slug: ivedha-tech/regression-m-17
    github.com/repo-url: https://github.com/ivedha-tech/regression-m-17
    backstage.io/source-location: https://github.com/ivedha-tech/regression-m-17
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/development-team
    release-manager/repository: regression-m-17-service-testjan
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/regression-m-17
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: regression-m-17-service-testjan
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: testjan
  owner: group:default/development-team
  system: system:default/Regression-17
  created_by: thushanthini.kulenthiran@ivedha.com
