apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regressionmarch273
  description: testing
  annotations:
    github.com/project-slug: ivedha-tech/regressionmarch3repo
    github.com/repo-url: https://github.com/ivedha-tech/regressionmarch3repo
    backstage.io/source-location: https://github.com/ivedha-tech/regressionmarch3repo
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/guests
    release-manager/repository: regressionmarch273
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/regressionmarch3repo
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: regressionmarch273tr
    google.com/cloudbuild-project-slug: prj-dev-platform-next  
    google.com/gcp-projectid: prj-dev-platform-next  
spec:
  type: service
  lifecycle: dit1
  owner: group:default/guests
  system: system:default/QA-Regression
  created_by: subas
