apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regression-qa-8-staging
  description: Backend
  annotations:
    github.com/project-slug: test-platformnex/regression-qa-gcon-1
    github.com/repo-url: https://github.com/test-platformnex/regression-qa-gcon-1
    backstage.io/source-location: https://github.com/test-platformnex/regression-qa-gcon-1
    backstage.io/language: typescript
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: regression-qa-8-staging
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/regression-qa-gcon-1
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: regression-qa-8-staging
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: regression-qa-8-staging

spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: thushanthini.kulenthiran@ivedha.com
