apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: REGTEST
  description: REGTEST
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-4-f-repo
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
