apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: release-uat-18
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prod-f-d-5
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " prod-f-d-5"
    google.com/cloudbuild-trigger-name: release-18-staging-trigger
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
