apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: remarch26
  description: Test tagline
  annotations:
    github.com/project-slug: ivedha-tech/regression26marchrepo
    github.com/repo-url: https://github.com/ivedha-tech/regression26marchrepo
    backstage.io/source-location: https://github.com/ivedha-tech/regression26marchrepo
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: remarch26
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/regression26marchrepo
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: remarch26tr
    google.com/cloudbuild-project-slug: prj-dev-platform-next 
    google.com/gcp-projectid: prj-dev-platform-next 
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: subas
