apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: restest0912
  description: sdfbv edit
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-qa1/applications/
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platfor-admin
  system: system:default/Reg-Test-0912
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prjt-id
  lifecycle: UAT
