apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rmtest
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Test-Application
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: github
