apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex_qa_automation
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-App-Automation-sa
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex_qa_automation
    backstage.io/source-vcs: github
