apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: salesforce-backend-dit2
  description: salesforce-backend-dit2
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-backend
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-forcenex-backend-dit2-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: dit2
  owner: group:default/platformnex-salesforce-team
  system: system:default/platformnex-salesforce
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-salesforce-backend
    backstage.io/source-vcs: github
