apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample_app_for_developer_test
  description: sample_app_for_developer_test
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
