apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: samplerepo
  description: https://github.com/Sakun-Weerasinghe/sample
  annotations:
    backstage.io/source-location: https://github.com/Sakun-Weerasinghe/sample
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/QA-Test-Application
