apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: samplecomponnt
  description: samplecomponnt
  annotations:
    backstage.io/source-location: https://github.com/Samadhi-Ivedha/Feature-testing
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/HelloWorld2
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/Samadhi-Ivedha/Feature-testing
    backstage.io/source-vcs: github
