apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sanity-rec
  description: sample
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platformnex-admin
  system: system:default/test-sanity-8-sep
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
