apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sasiru-12321
  description: storage resource for helloworld
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/cloudrun-project-slug: prj-dev-platform-test
    google.com/cloudrun-location: us
    google.com/cloudrun-service-name: prj
    google.com/cloudbuild-trigger-name: hello-world-trigger-69b040cf-49ce-448a-a784-c7536adc4b29
    google.com/cloudbuild-project-slug: prj-dev-platform-test
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: storage
  lifecycle: dit1
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/helloworld
  providesApis: []
  consumesApis: []
