apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sasiru-bb123
  description: storage resource for Dev-Test
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: storage
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/Dev-Test
  lifecycle: development
