apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sasiru-bucket
  description: Existing storage resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/platformnex-team
  system: system:default/Catalog-test
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: catalog-test__development
