apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sasiru-test-component
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/psychic-waffle
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/platformnex
  dependsOn: []
  dependencyOf: []
