apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sasiru-bucket
  description: Existing storage resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: storage
  owner: group:default/guests
  system: system:default/BranchTest
  region: US-CENTRAL1
  project: prj-dev-platform-next
  lifecycle: development
  created_by: sanuka.dayarathne@ivedha.com

