apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secret-manager-dev
  description: secret manager for dev instance
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/secret-manager
    backstage.io/source-vcs: Github
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/platformnex
