apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-service-external-connector-UAT
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/security-service-external-connector
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: security-service-external-connector-UAT1
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  system: system:default/Security-Service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/security-service-external-connector
    backstage.io/source-vcs: github
