apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-application-development
  description: This is the servicenex development app
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: servicenex
    google.com/cloudrun-project-slug: prj-dev-service-nex
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: servicenex-dit
    google.com/cloudbuild-trigger-name: SERVICENEX-DIT-QA
    google.com/cloudbuild-project-slug: prj-dev-service-nex
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-platformnex-prod
    jira.com/project-key: cws
spec:
  type: website
  lifecycle: servicenex-DIT
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex
    backstage.io/source-vcs: github
