apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: servicenex-prod
  description: This is the servicenex prod service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: servicenex
    google.com/cloudrun-project-slug: prj-servicenex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: servicenex-prod
    google.com/cloudbuild-trigger-name: SERVICENEX-PROD
    google.com/cloudbuild-project-slug: prj-servicenex-prod
    google.com/cloudbuild-location: us-central1
    jira.com/project-key: CWS
spec:
  type: website
  lifecycle: uat
  owner: group:default/platformnex-admin
  system: system:default/servicenex
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex
    backstage.io/source-vcs: github
