apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snk-003
  description: test
  annotations:
    github.com/project-slug: ivedha-tech/sanuka-qa1-003-fee
    github.com/repo-url: https://github.com/ivedha-tech/sanuka-qa1-003-fee
    backstage.io/source-location: https://github.com/ivedha-tech/sanuka-qa1-003-fee
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/development-team
    release-manager/repository: snk-003
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/sanuka-qa1-003-fee
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: sanuka-qa1-003-tr
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: dev
  owner: group:default/development-team
  system: system:default/Platformnex-Regression
  created_by: sanuka
