apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: st
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-repo-sep-29-f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
    jira.com/project-key: PEJ
    sonarqube.org/project-key: qa-repo-sep-29-f
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/Regression-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-repo-sep-29-f
    backstage.io/source-vcs: github
