apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-10
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/dev-regression-f-m-10
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: dev-regression-f-m-10
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/platform-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
