apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-f-27-tc
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/Test-Application
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-f-27-tc
    backstage.io/source-vcs: github
