apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-regression-f-22
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/tech-regression-f-22
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " tech-regression-f-22"
    google.com/gcp-projectid: ""
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: staging
  owner: group:default/development-team
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
