apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: staging-sanity-env
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/sanity-f-PE-8
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
    google.com/cloudbuild-trigger-name: staging-sanity-env-staging-trigger
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
