apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-regression-18
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-regression-feb-f-18
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " qa-regression-feb-f-18"
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: staging
  owner: group:default/development-team
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
