apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-yy
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-21-f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/development-team
  system: system:default/Regression-8
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-21-f
    backstage.io/source-vcs: github
