apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-hotfix-20
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-pn-f-21
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-pn-f-21
    backstage.io/source-vcs: github
