apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-release-20
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/release-20-f
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: " release-20-f"
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex-Regression
  providesApis: []
  consumesApis: []
