apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regression-repo-5-f
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Regression-test
  providesApis: []
  consumesApis: []
