apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stage-env-reg-20
  description: stage-env-reg-20
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regtestrepo-f-aug-20
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/Test-Application
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regtestrepo-f-aug-20
    backstage.io/source-vcs: github
