apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: talentnex-frontend-dit1
  description: talentnex-frontend-dit1 service
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/cauldron-frontend
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: prj-dev-talent-nex
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: talentnex-frontend-dit1
    google.com/cloudbuild-trigger-name: TALENTNEX-FRONTEND-DIT-1
    google.com/cloudbuild-project-slug: prj-dev-talent-nex
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: dit1
  owner: group:default/talentnex-team
  dependsOn: []
  dependencyOf: []
  system: system:default/talentnex
  providesApis: []
  consumesApis: []
