apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: talentnex
  description: this is talentnex application
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/talentnex-team
