apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tatab-prod
  description: https://github.com/ivedha-tech/tatab
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/tatab
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-Application
