apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tech-prod-development
  description: Backend
  annotations:
    github.com/project-slug: ivedha-tech/gc-regression-pe
    github.com/repo-url: https://github.com/ivedha-tech/gc-regression-pe
    backstage.io/source-location: https://github.com/ivedha-tech/gc-regression-pe
    backstage.io/language: typescript
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: tech-prod-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/gc-regression-pe
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: tech-prod-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: thushanthini.kulenthiran@ivedha.com
