apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tech-prod-27-b-service-staging
  description: backend component
  annotations:
    github.com/project-slug: ivedha-tech/tech-prod-27-b
    github.com/repo-url: https://github.com/ivedha-tech/tech-prod-27-b
    backstage.io/source-location: https://github.com/ivedha-tech/tech-prod-27-b
    backstage.io/language: go
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: tech-prod-27-b-service-staging
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/tech-prod-27-b
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: tech-prod-27-b-service-staging
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: staging
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: thushanthini.kulenthiran@ivedha.com
