apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tempTest2
  description: test
  annotations:
    github.com/project-slug: ivedha-tech/faheemTemplateTest2
    github.com/repo-url: https://github.com/ivedha-tech/faheemTemplateTest2
    backstage.io/source-location: https://github.com/ivedha-tech/faheemTemplateTest2
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platfor-admin
    release-manager/repository: tempTest2
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/faheemTemplateTest2
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: tempTestCI2
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platfor-admin
  system: system:default/testingFrontend
  created_by: faheem
