apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-new-greenfield-onboard-service-branch-env
  description: created by template
  annotations:
    github.com/project-slug: test-platformnex/test-new-greenfield-onboard
    github.com/repo-url: https://github.com/test-platformnex/test-new-greenfield-onboard
    backstage.io/source-location: https://github.com/test-platformnex/test-new-greenfield-onboard
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/guests
    release-manager/repository: test-new-greenfield-onboard-service-branch-env
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/test-new-greenfield-onboard
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: test-new-greenfield-onboard-service-branch-env
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: branch-env
  owner: group:default/guests
  system: system:default/BranchTest
  created_by: ama.perera@ivedha.com
