apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Test-App-3
  description: Test-App-3
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
