apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-test-t-21-service-development
  description: created by template
  annotations:
    github.com/project-slug: test-platformnex/test-test-t-21
    github.com/repo-url: https://github.com/test-platformnex/test-test-t-21
    backstage.io/source-location: https://github.com/test-platformnex/test-test-t-21
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/development-team
    release-manager/repository: test-test-t-21-service-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/test-test-t-21
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: test-test-t-21-service-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-project-slug: values.cloudbuild_project_slug || "
    google.com/cloudrun-location: values.cloudbuild_location || "us-central1

spec:
  type: service
  lifecycle: development
  owner: group:default/development-team
  system: system:default/regression-test-13
  created_by: thushanthini.kulenthiran@ivedha.com
