apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Test-App-Automation-1758297707265
  description: Sample App
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
