apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-lc
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/private23f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Regression-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/private23f
    backstage.io/source-vcs: github
