apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test
  description: testtesttesttesttesttesttest
  annotations:
    backstage.io/source-location: url:https://testrepo.com
    backstage.io/source-vcs: Github
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
