apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-final-99-service-development
  description: created by template
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-final-99
    backstage.io/source-vcs: Github
    github.com/project-slug: ivedha-tech/test-final-99
    github.com/repo-url: https://github.com/ivedha-tech/test-final-99
    google.com/cloudbuild-trigger-name: test-final-99-service-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: prj-dev-platform-next
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-team
  system: system:default/Dit1-Application
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-final-99
    backstage.io/source-vcs: github
