apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-so-nn11-stage
  description: https://github.com/ivedha-tech/test-so-nn11
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-so-nn11
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: staging
  owner: group:default/guests
  system: system:default/Test-App
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-so-nn11
    backstage.io/source-vcs: github
