apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-am
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-devops-gateway
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: prj-dev-platform-next
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: platformnex-test__development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/platformnex-test
  providesApis: []
  consumesApis: []
