apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-vp
  description: test-vp
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/prj-dev-platform-next
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/guests
  system: system:default/Platformnex
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: staging
