apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-security-analysis
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/cgs-tech/cgs-test-app
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platform-admin
  system: system:default/Platformnex-Regression
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/cgs-tech/cgs-test-app
    backstage.io/source-vcs: github
