apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-25-development
  description: Backend
  annotations:
    github.com/project-slug: ivedha-tech/repo-uat-f-24
    github.com/repo-url: https://github.com/ivedha-tech/repo-uat-f-24
    backstage.io/source-location: https://github.com/ivedha-tech/repo-uat-f-24
    backstage.io/language: typescript
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platform-admin
    release-manager/repository: test-25-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/repo-uat-f-24
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: test-25-development
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: service
  lifecycle: development
  owner: group:default/platform-admin
  system: system:default/Platformnex-Regression-24
  created_by: thushanthini.kulenthiran@ivedha.com
