apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-comp-sonar
  description: test-comp-sonartest-comp-sonar
  annotations:
    backstage.io/source-location: https://github.com/kushanD95/swag-test-temp100
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/QA-Test-Application
  providesApis: []
  consumesApis: []
