apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-resource
  description: gggggggggggggggggggggggggggggggggggggggggggggggggggggggg
spec:
  type: storage
  owner: group:default/guests
  region: us-central1
  project: prj-platform-next
