apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-app-123456789
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/ga-test-004-fe
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/local-test-004
  system: system:default/ga-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/ga-test-004-fe
    backstage.io/source-vcs: github
