apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-0001-cache
  description: test-0001-cache
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/guests
