apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-prebugfix78
  description: test-prebugfix78 description goes here
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug1
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-Application
  dependsOn: []
  dependencyOf: []
