apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-july17-qa
  description: testing
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: regression-test__development
  owner: group:default/development-team
  system: system:default/Regression-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: github
