apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: TestAPI-1759315392633
  description: Sample API
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: openapi
  lifecycle: development
  owner: group:default/guests
  system: system:default/Regression-test
  definition: Defining the api
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: github
