apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api
  description: jhnjhiuh
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex_qa_automation
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: openapi
  lifecycle: production
  owner: group:default/platformnex-admin
  system: system:default/Test-Application
  definition: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex_qa_automation
    backstage.io/source-vcs: github
