apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test56
  description: y
  annotations:
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/guests
  system: system:default/test
  region: us-central1
  project: esf
  lifecycle: QA
