apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-repo-sep-29-f
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-projectid: prj-dev-platform-next
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/reg26sep-ssg
  providesApis: []
  consumesApis: []
