apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: teststorage-2014d51
  description: Existing storage resource mapped from Map Existing step
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: storage
  owner: group:default/platformnex-team
  system: system:default/Catalog-test
  region: US-CENTRAL1
  project: prj-dev-platform-next
  lifecycle: development
  created_by: nithursika.kalanantharasan@ivedha.com

