apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-v-comp
  description: Using this for test purposes of CI/CD configuration
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/vinoli-cicd-1
    backstage.io/source-vcs: Github
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/QA-Test-Application
