apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TestComponentAuto-1756965452791
  description: Sample Component
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-App-Automation-1756965435390
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/platformnex-frontend
    backstage.io/source-vcs: github
