apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-test-qa-456
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qatest23front
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: test-test-qa-456-development-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/RM-Test
  providesApis: []
  consumesApis: []
