apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testTemp1
  description: test
  annotations:
    github.com/project-slug: ivedha-tech/testTempFaheem1
    github.com/repo-url: https://github.com/ivedha-tech/testTempFaheem1
    backstage.io/source-location: https://github.com/ivedha-tech/testTempFaheem1
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platfor-admin
    release-manager/repository: testTemp1
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/testTempFaheem1
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: testTemp1
    google.com/cloudbuild-project-slug: testTemp1
    google.com/gcp-projectid: testTemp1
spec:
  type: service
  lifecycle: dit1
  owner: group:default/platfor-admin
  system: system:default/new-app-fin
  created_by: faheem
