apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testresource
  description: testing edited
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-qa1/applications/
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/guests
  system: system:default/reg-test-26-aug
  dependsOn: []
  dependencyOf: []
  region: us-central1
  project: prj-dev-platform-next
  lifecycle: development
