apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-123-res
  description: kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
spec:
  type: storage
  owner: group:default/guests
  system: system:default/Platformnex
  region: us-central1
  project: prj-platform-next
