apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-repo-sep-29-f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/platfor-admin
  system: system:default/reg26sep-ssg
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qa-repo-sep-29-f
    backstage.io/source-vcs: github
