apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-navee-service-uat
  description: created by template
  annotations:
    github.com/project-slug: test-platformnex/test-navee
    github.com/repo-url: https://github.com/test-platformnex/test-navee
    backstage.io/source-location: https://github.com/test-platformnex/test-navee
    backstage.io/language: typescript
    backstage.io/framework: react
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: test-navee-service-uat
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/test-platformnex/test-navee
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: test-navee-service-uat
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-project-slug: values.cloudbuild_project_slug || "
    google.com/cloudrun-location: values.cloudbuild_location || "us-central1

spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  system: system:default/Regression-6
  created_by: subas.thayananthan@ivedha.com
