apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-qa-789
  description: test
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qatest23front
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: staging
  owner: group:default/guests
  system: system:default/RM-Test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/qatest23front
    backstage.io/source-vcs: github
