apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-y-development
  description: Backend
  annotations:
    github.com/project-slug: ivedha-tech/dev-test
    github.com/repo-url: https://github.com/ivedha-tech/dev-test
    backstage.io/source-location: https://github.com/ivedha-tech/dev-test
    backstage.io/language: typescript
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: test-y-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/dev-test
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: dev-test-service-development-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/gcp-projectid: prj-dev-platform-next
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: dev-test-service-development

spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Regression-6
  created_by: thushanthini.kulenthiran@ivedha.com
