apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-onboard-brown-june-development
  description: Backend
  annotations:
    github.com/project-slug: ivedha-tech/platform-orchestrator-core
    github.com/repo-url: https://github.com/ivedha-tech/platform-orchestrator-core
    backstage.io/source-location: https://github.com/ivedha-tech/platform-orchestrator-core
    backstage.io/language: rust
    backstage.io/framework: gin
    release-manager/repository-owner: group:default/platformnex-admin
    release-manager/repository: test-onboard-brown-june-development
    release-manager/branching-strategy: TBD
    release-manager/auth-provider: github
    repo-url: https://github.com/ivedha-tech/platform-orchestrator-core
    backstage.io/source-vcs: Github
    google.com/cloudbuild-location: us-central1
    google.com/cloudbuild-trigger-name: test-onboard-brown-june-development
    google.com/cloudbuild-project-slug: prj-platformnex-prod
    google.com/gcp-projectid: prj-platformnex-prod
    google.com/cloudrun-project-slug: prj-platformnex-prod
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: test-onboard-brown-june-development
    platformnex.io/deployment-destination: 
    argocd.platformnex.io/instance: 
    argocd.platformnex.io/project: 
    argocd.platformnex.io/namespace: 
    argocd.platformnex.io/destination-namespace: 
    argocd.platformnex.io/application-name: 
    gitops.platformnex.io/repo-url: 
    gitops.platformnex.io/branch: 
    gitops.platformnex.io/environment-path: 
spec:
  type: service
  lifecycle: development
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  created_by: subas.thayananthan@ivedha.com
