apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: regression test description
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regressionrepo-qa-f-12
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: regressionrepo-qa-f-12-cacd6-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  dependsOn: []
  dependencyOf: []
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
