apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-june-1313
  description: storage resource for BranchTest
  annotations:
    backstage.io/source-location: https://github.com/prj-dev-platform-next
    backstage.io/source-vcs: github
    google.com/gcp-projectid: ""
spec:
  type: storage
  region: us-central1
  project: prj-dev-platform-next
  owner: group:default/guests
  system: system:default/BranchTest
  lifecycle: branchtest__develop
