apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testrepo-qa-f-aug-6
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
    jira.com/project-key: PEJ
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/testrepo-qa-f-aug-6
    backstage.io/source-vcs: github
