apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-ama-new
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-platformnex-frontend-dit1-nonprod
    google.com/cloudbuild-project-slug: ivedha-workload-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ivedha-workload-env-nonprod
spec:
  type: service
  lifecycle: platformnex-test__development
  owner: group:default/guests
  system: system:default/platformnex-test
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/test-platformnex/qa-re-1
    backstage.io/source-vcs: github
