apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testNEWD
  description: F
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regressionrepo-qa-f-12
    backstage.io/source-vcs: Github
    google.com/cloudrun-project-slug: ""
    google.com/cloudrun-location: ""
    google.com/cloudrun-service-name: ""
    google.com/gcp-projectid: ""
    google.com/cloudbuild-trigger-name: testrepo-qa-f-aug1-2bf2e-trigger
    google.com/cloudbuild-project-slug: TESTNEWD
    google.com/cloudbuild-location: us-central1
spec:
  type: service
  lifecycle: production
  owner: group:default/guests
  system: system:default/Platformnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/regressionrepo-qa-f-12
    backstage.io/source-vcs: github
