apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-releasemanager-dev
  description: https://github.com/ivedha-tech/test-releasemanager
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-releasemanager
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-dev-platform-next
spec:
  type: website
  lifecycle: development
  owner: group:default/guests
  system: system:default/Test-App
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-releasemanager
    backstage.io/source-vcs: github
