apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testdm
  description: https://github.com/ivedha-tech/remo-uatf
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/remo-uatf
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Platformnex
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/remo-uatf
    backstage.io/source-vcs: github
