apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: trustnex-frontend-dit2
  description: trustnex-frontend service dit2
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/Trustnex-frontend
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-trustnex-frontend-dit2-nonprod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-nonprod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: dit2
  owner: group:default/trustnex-admin
  system: system:default/trustnex
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/Trustnex-frontend
    backstage.io/source-vcs: github
