apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tvtv
  description: we
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  type: storage
  owner: group:default/guests
  system: system:default/Platformnex
  region: us-central1
  project: wed
  lifecycle: development
