apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: uat-27
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/tech-prod-19-f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: prj-platformnex-prod
spec:
  type: service
  lifecycle: uat
  owner: group:default/platformnex-admin
  system: system:default/Platformnex-Regression
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/tech-prod-19-f
    backstage.io/source-vcs: github
