apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: uat-reg-comp-10-08
  description: reg comp
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/test-qa-f-15
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: platformnex
    google.com/cloudrun-project-slug: prj-dev-platform-next
    google.com/cloudrun-location: us-central1
    google.com/cloudrun-service-name: platformnex-v2-frontend-dit2
    google.com/gcp-projectid: ""
    google.com/cloudbuild-trigger-name: uat-reg-comp-10-08-development-trigger
    google.com/cloudbuild-project-slug: prj-dev-platform-next
    google.com/cloudbuild-location: us-central1
spec:
  type: website
  lifecycle: development
  owner: group:default/platform-admin
  dependsOn: []
  dependencyOf: []
  system: system:default/uat-reg-10-08
  providesApis: []
  consumesApis: []
