apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: uat-reg-10-08
  description: reg10-08
  annotations:
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ""
spec:
  owner: group:default/platform-admin
