apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: uat-ry
  description: ''
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-21-f
    backstage.io/source-vcs: Github
    google.com/gcp-projectid: ''
    sonarqube.org/project-key: repo-21-f
spec:
  type: service
  lifecycle: uat
  owner: group:default/platform-admin
  system: system:default/PE-regression-22
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/repo-21-f
    backstage.io/source-vcs: github
