apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Workbeam-Backend
  description: Workbeam backend services.
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/workbeam
    backstage.io/source-vcs: Github
    sonarqube.org/project-key: workbeam
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Workbeam
