apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Workbeam-Backend
  description: The backend server for workbeam
  annotations:
    backstage.io/source-location: url:https://github.com/ivedha-tech/workbeam
    backstage.io/source-vcs: Github
    jira.com/project-key: ""
    mycompany.com/gcp-dataset-id: ds_billing
    mycompany.com/gcp-provider: gcp
    mycompany.com/gcp-table-id: gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: system:default/Workbeam
