apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: satckover23
  title: satckover231
  description: stackovertesting1
  tags: []
  namespace: default
  type: ""
  annotations:
    backstage.io/managed-by-location: url:https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/satckover23.yaml
    backstage.io/managed-by-origin-location: url:https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/satckover23.yaml
    backstage.io/view-url: https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/satckover23.yaml
spec:
  owner: development-team
  type: yaml
  parameters:
    - title: Basic Information
      required:
        - component_id
        - owner
        - system
        - component_type
        - environments
      properties:
        component_id:
          title: Component ID
          type: string
          ui:field: EntityNamePicker
          maxLength: 64
          pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description:
          title: Description
          type: string
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System
        component_type:
          title: Component Type
          type: string
          enum:
            - Frontend
            - Backend
          default: Frontend
        deployment:
          title: Deployment Platform
          type: string
          description: Deployment platform (e.g., gcp, aws, azure)
        environments:
          title: Environments
          type: array
          items:
            type: string
            enum:
              - dev
              - qa
              - staging
              - prod
          ui:widget: checkboxes
    - title: Configuration
      dependencies:
        component_type:
          oneOf:
            - properties:
                component_type:
                  const: Frontend
                frontend_framework:
                  title: Frontend Framework
                  type: string
                  enum:
                    - React
                  default: React
                frontend_language:
                  title: Frontend Language
                  type: string
                  enum:
                    - TypeScript
                  default: TypeScript
                frontend_styling:
                  title: Frontend Styling
                  type: string
                  enum:
                    - TailwindCSS
                    - Material-UI
                  default: TailwindCSS
                frontend_state:
                  title: Frontend State
                  type: string
                  enum:
                    - Redux-Toolkit
                    - None
                  default: None
                frontend_service_repository:
                  title: Frontend Service Repository
                  type: string
                  ui:field: RepoUrlPicker
                  ui:options:
                    allowedHosts:
                      - github.com
                frontend_service_branch:
                  title: Frontend Service Branch
                  type: string
                  default: main
              required:
                - frontend_framework
                - frontend_language
                - frontend_service_repository
                - frontend_service_branch
            - properties:
                component_type:
                  const: Backend
                backend_language:
                  title: Backend Language
                  type: string
                  enum:
                    - Go
                  default: Go
                backend_framework:
                  title: Backend Framework
                  type: string
                  dependencies:
                    backend_language:
                      Go:
                        enum:
                          - Gin
                        default: Gin
                      Node.js:
                        enum:
                          - Express
                          - NestJS
                        default: Express
                  default: Gin
                backend_service_repository:
                  title: Backend Service Repository
                  type: string
                  ui:field: RepoUrlPicker
                  ui:options:
                    allowedHosts:
                      - github.com
                backend_service_branch:
                  title: Backend Service Branch
                  type: string
                  default: main
              required:
                - backend_language
                - backend_framework
                - backend_service_repository
                - backend_service_branch
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/ivedha-tech/platformnex-templates/tree/main/repos/backend-go-gin
        targetPath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
    - id: greenfield-pre-req-1
      name: Setup Prerequisites
      action: greenfield:pre-req
      input:
        repoUrl: ${{ (parameters.component_type == 'Frontend' and parameters.frontend_service_repository) or parameters.backend_service_repository }}
        deploymentPlatform: ${{ parameters.deployment | lower }}
        system: ${{ parameters.system }}
        owner: ${{ parameters.owner }}
    - id: publish-github-2
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ (parameters.component_type == 'Frontend' and parameters.frontend_service_repository) or parameters.backend_service_repository }}
        sourcePath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
        defaultBranch: ${{ (parameters.component_type == 'Frontend' and parameters.frontend_service_branch) or parameters.backend_service_branch }}
        allowedHosts:
          - github.com
  output:
    links:
      - title: Repository
        url: ${{ steps['publish-github-2'].output.remoteUrl }}
