apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sdfghjkikm
  title: sdfghjkikm
  description: qwertyuiop
spec:
  owner: test-backstage-001
  type: yaml
parameters:
  - title: "Basic Information"
    required: ["component_id", "owner"]
    properties:
      component_id:
        title: "Component ID"
        type: string
        ui:
          field: EntityNamePicker
        maxLength: 64
        pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
      description:
        title: "Description"
        type: string
      owner:
        title: "Owner"
        type: string
        ui:
          field: OwnerPicker
      system:
        title: "System"
        type: string
        ui:
          field: EntityPicker
          options:
            catalogFilter:
              kind: System
      component_type:
        title: "Component Type"
        type: string
        enum: [Frontend, Backend]
        default: Frontend
      environments:
        title: "Environments"
        type: array
        items:
          type: string
          enum: [dev, qa, staging, prod]
        ui:
          widget: checkboxes

  - title: "Configuration"
    properties:
      component_type:
        title: "Component Type"
        type: string
      dependencies:
        component_type:
          oneOf:
            - properties:
                component_type:
                  const: Frontend
                frontend_framework:
                  title: "Frontend Framework"
                  type: string
                  enum: [React]
                  default: React
                frontend_language:
                  title: "Frontend Language"
                  type: string
                  enum: [TypeScript]
                  default: TypeScript
                frontend_styling:
                  title: "Frontend Styling"
                  type: string
                  enum: [TailwindCSS, Material-UI]
                  default: TailwindCSS
                frontend_state:
                  title: "Frontend State"
                  type: string
                  enum: [Redux-Toolkit, None]
                  default: Redux-Toolkit
                frontend_service_repository:
                  title: "Frontend Service Repository"
                  type: string
                  ui:
                    field: RepoUrlPicker
                frontend_service_branch:
                  title: "Frontend Service Branch"
                  type: string
                  default: main
              required:
                - frontend_framework
                - frontend_language
                - frontend_service_repository
                - frontend_service_branch
            - properties:
                component_type:
                  const: Backend
                backend_language:
                  title: "Backend Language"
                  type: string
                  enum: [Go, Node.js]
                  default: Go
                backend_framework:
                  title: "Backend Framework"
                  type: string
                  dependencies:
                    backend_language:
                      Go:
                        enum: ['Gin']
                        default: Gin
                      Node.js:
                        enum: ['Express', 'NestJS']
                        default: Express
                  default: Gin
                backend_service_repository:
                  title: "Backend Service Repository"
                  type: string
                  ui:
                    field: RepoUrlPicker
                backend_service_branch:
                  title: "Backend Service Branch"
                  type: string
                  default: main
              required:
                - backend_language
                - backend_framework
                - backend_service_repository
                - backend_service_branch

  - title: "CICD and Specs"
    properties:
      cloudbuild_yaml:
        title: "Cloudbuild YAML"
        type: string
        ui:
          widget: textarea
      specs_yaml:
        title: "Specs YAML"
        type: string
        ui:
          widget: textarea

  - title: "Catalog Information"
    properties:
      catalog_info_dev_yaml:
        title: "Catalog Info Dev YAML"
        type: string
        ui:
          widget: textarea
      catalog_info_qa_yaml:
        title: "Catalog Info QA YAML"
        type: string
        ui:
          widget: textarea
      catalog_info_staging_yaml:
        title: "Catalog Info Staging YAML"
        type: string
        ui:
          widget: textarea
      catalog_info_prod_yaml:
        title: "Catalog Info Prod YAML"
        type: string
        ui:
          widget: textarea
      catalog_repo_url:
        title: "Catalog Repo URL"
        type: string
      catalog_file_dir:
        title: "Catalog File Directory"
        type: string
        default: applications

  - title: "Infrastructure Options"
    properties:
      iac_dev_json:
        title: "IaC Dev JSON"
        type: string
        ui:
          widget: textarea
      iac_qa_json:
        title: "IaC QA JSON"
        type: string
        ui:
          widget: textarea
      iac_staging_json:
        title: "IaC Staging JSON"
        type: string
        ui:
          widget
steps:
  - id: fetch-template
    name: Fetch Template
    action: fetch:template
    input:
      url: "./template/repos/node"
      targetPath: ${{ parameters.component_type == 'Frontend' ? './frontend' : './backend' }}

  - id: greenfield-pre-req-1
    name: Setup Prerequisites
    action: greenfield:pre-req
    input:
      repoUrl: ${{ parameters.component_type == 'Frontend' ? parameters.frontend_service_repository : parameters.backend_service_repository }}
      deploymentPlatform: ${{ parameters.deployment | lower }}
      system: ${{ parameters.system }}
      owner: ${{ parameters.owner }}

  - id: greenfield-write-yaml-2
    name: Write YAML File
    action: greenfield:write-yaml
    input:
      yamlContent: ${{ parameters.cloudbuild_yaml }}
      targetPath: ${{ parameters.component_type == 'Frontend' ? './frontend' : './backend' }}
      fileName: 'cloudbuild.yaml'

  - id: greenfield-write-and-onboard-catalog-3
    name: Write and Onboard Catalog
    action: greenfield:write-and-onboard-catalog
    input:
      componentType: ${{ parameters.component_type }}
      componentId: ${{ parameters.component_id }}
      environments: ${{ parameters.environments }}
      catalogRepoTreeUrl: ${{ parameters.catalog_repo_url }}
      catalogFileDir: ${{ parameters.catalog_file_dir }}
      catalogFileNamePrefix: ${{ parameters.component_id }}
      catalog_info_dev_yaml: ${{ parameters.catalog_info_dev_yaml }}
      catalog_info_qa_yaml: ${{ parameters.catalog_info_qa_yaml }}
      catalog_info_staging_yaml: ${{ parameters.catalog_info_staging_yaml }}
      catalog_info_prod_yaml: ${{ parameters.catalog_info_prod_yaml }}

  - id: publish-github-4
    name: Publish to GitHub
    action: publish:github
    input:
      repoUrl: ${{ parameters.component_type == 'Frontend' ? parameters.frontend_service_repository : parameters.backend_service_repository }}
      sourcePath: ${{ parameters.component_type == 'Frontend' ? './frontend' : './backend' }}
      defaultBranch: ${{ parameters.component_type == 'Frontend' ? parameters.frontend_service_branch : parameters.backend_service_branch }}
      allowedHosts: ["github.com"]

  - id: catalog-register-5
    name: Register Catalog
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps['greenfield-write-and-onboard-catalog-3'].output.repoContentsUrl }}
      catalogInfoPath: ${{ '/' + parameters.catalog_file_dir + '/' + steps['greenfield-write-and-onboard-catalog-3'].output.fileNames.dev }}

  - id: greenfield-execute-iac-6
    name: Execute IAC
    action: greenfield:execute-iac
    input:
      orchestratorBaseUrl: ${{ parameters.orchestrator_base_url }}
      environments: ${{ parameters.environments }}
      iac_dev_json: ${{ parameters.iac_dev_json }}
      iac_qa_json: ${{ parameters.iac_qa_json }}
      iac_staging_json: ${{ parameters.iac_staging_json }}
      iac_prod_json: ${{ parameters.iac_prod_json }}
output:
  links:
    - title: Repository
      url: ${{ steps['publish-github-4'].output.remoteUrl }}
