apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: stack23
  title: stack23
  description: stack testing
spec:
  owner: development-team
  type: yaml
  parameters:
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: "https://github.com/ivedha-tech/platformnex-templates/tree/main/repos/frontend-react-typescript-material-ui-none"
        targetPath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
  output:
    links: []
