apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-003
  title: template-003
  description: QA test for template
  tags: []
  namespace: default
  type: ""
  annotations:
    backstage.io/managed-by-location: url:https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/template-003.yaml
    backstage.io/managed-by-origin-location: url:https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/template-003.yaml
    backstage.io/view-url: https://raw.githubusercontent.com/ivedha-tech/cloud_configs/feature-yaml-qa1/company/7/templates/template-003.yaml
spec:
  owner: management-team
  type: yaml
  steps:
    - id: fetch-catalog-tools
      name: Fetch Catalog Tools
      action: fetch:template
      input:
        url: https://github.com/ivedha-tech/platformnex-templates/blob/main/default-entities
        targetPath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
        values:
          integrationHost: ${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("?")[0] }}
          repo: ${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("repo=")[1] }}
          slug: ${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("owner=")[1].split("&")[0] }}/${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("repo=")[1] }}
          environment: ${{ parameters.environments[0] || "dev" }}
          owner: ${{ parameters.owner }}
          system_name: ${{ parameters.system }}
          repo_url: https://github.com/${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("owner=")[1].split("&")[0] }}/${{ ((parameters.component_type == "Frontend" and parameters.frontend_service_repository) or parameters.backend_service_repository).split("repo=")[1] }}
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/ivedha-tech/platformnex-templates/tree/main/repos/frontend-react-typescript-tailwindcss-redux-toolkit
        targetPath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
    - id: publish-github-1
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ (parameters.component_type == 'Frontend' and parameters.frontend_service_repository) or parameters.backend_service_repository }}
        sourcePath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
        defaultBranch: ${{ (parameters.component_type == 'Frontend' and parameters.frontend_service_branch) or parameters.backend_service_branch }}
        allowedHosts:
          - github.com
    - id: catalog-register-2
      name: Register Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-github-1'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps['publish-github-1'].output.remoteUrl }}
