apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test67
  title: test67
  description: testingtesting
spec:
  owner: development-team
  type: yaml
  parameters:
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: "https://github.com/ivedha-tech/platformnex-templates/tree/main/repos/frontend-react-typescript-material-ui-redux-toolkit"
        targetPath: ${{ (parameters.component_type == 'Frontend' and './frontend') or './backend' }}
  output:
    links: []
