apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: abc_repo_genaaaaaaaa
  title: repogenaaaaaaaa
  description: repository gen template
  tags: []
  namespace: default
  type: ""
  annotations:
    backstage.io/managed-by-location: url:https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-dit1/templates/abc_repo_genaaaaaaaa.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/ivedha-tech/cloud_configs/blob/feature-yaml-dit1/templates/abc_repo_genaaaaaaaa.yaml
    backstage.io/view-url: https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-dit1/templates/abc_repo_genaaaaaaaa.yaml
    backstage.io/edit-url: https://github.com/ivedha-tech/cloud_configs/edit/feature-yaml-dit1/templates/abc_repo_genaaaaaaaa.yaml
    backstage.io/source-location: url:https://github.com/ivedha-tech/cloud_configs/tree/feature-yaml-dit1/templates/
spec:
  owner: platform-group
  type: yaml
  parameters:
    - title: Repository Configurationmmmm
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            default: github.com
    - title: Environment & Applicationmmmm
      required:
        - environment
        - application
      properties:
        environment:
          title: Environment
          type: string
          description: Target environment (development, staging, production)
        application:
          title: Application
          type: string
          description: Application name or type
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/ivedha-tech/platformnex-templates/tree/main/repos/frontend-react-typescript-tailwindcss-none
    - id: fetch-catalog-tools
      name: Fetch Catalog Tools
      action: fetch:template
      input:
        values:
          repo: ${{ parameters.repoUrl.split("repo=")[1] }}
          slug: ${{ parameters.repoUrl.split("owner=")[1].split("&")[0] }}/${{ parameters.repoUrl.split("repo=")[1] }}
          system: ${{ parameters.application }}
          owner: ${{ parameters.owner }}
          repo_url: https://github.com/${{ parameters.repoUrl.split("owner=")[1].split("&")[0] }}/${{ parameters.repoUrl.split("repo=")[1] }}
        targetPath: .
        url: https://github.com/ivedha-tech/platformnex-templates/blob/main/default-entities
    - id: publish-github
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
    - id: catalog-register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish-github.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps.publish-github.output.remoteUrl }}
